Store-apps-service.
rubrum-technologies/platform pull request #11
Opened 2024-10-03 20:47 UTC by vazgmik

2024-10-13 16:26 UTC, Veribelll requested changes

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/DeleteAppCommand.cs
> +            var app = await repository.GetAsync(x => x.Id == request.Id, true, cancellationToken);
Вместо этого `x => x.Id == request.Id`, можно просто передать `request.Id`

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/DeactivateAppCommand.cs
> +            var app = await repository.GetAsync(x => x.Id == request.Id, true, cancellationToken);
Вместо этого `x => x.Id == request.Id`, можно просто передать `request.Id`

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/CreateAppCommand.cs
> +                .MaximumLength(AppConstants.MaxNameLength);
Нет проверки на пустую строку

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/ChangeAppNameCommand.cs
> +            var app = await repository.GetAsync(x => x.Id == request.Id, true, cancellationToken);
Вместо этого `x => x.Id == request.Id`, можно просто передать `request.Id`

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/ChangeAppNameCommand.cs
> +            return app;
Нет обновления в репозитории

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/ChangeAppNameCommand.cs
> +    public required string Name { get; init; }
Нет валидатора на наименование

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.EntityFrameworkCore/Migrations/20240910085058_Initial.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Удали полностью миграцию и пере генерируй ее, сейчас она не правильная

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.EntityFrameworkCore/StoreAppsServiceDbContext.cs
> +    : AbpDbContext<StoreAppsServiceDbContext>(options)
Унаследуй от RubrumDbContext

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.EntityFrameworkCore/StoreAppsServiceDbContextModelCreatingExtensions.cs
> +                });
Сделай через ComplexProperty

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/Controllers/HomeController.cs
> +        return Redirect("~/api/swagger");
Переделай переадресацию на `~/graphql`

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/GraphqlGenerationModule.cs
> +[DependsOn<RubrumGraphqlModule>]
Модули только такие

```
[DependsOn<AbpAspNetCoreMvcModule>]
[DependsOn<RubrumGraphqlAuthorizationSpiceDbModule>]
```

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/GraphqlGenerationModule.cs
> +            .AddProjections();
Должно выглядеть так

```
        context.Services
            .GetGraphql()
            .AddGraphQLServer()
            .AddGlobalObjectIdentification()
            .AddQueryConventions()
            .AddMutationConventions()
            .AddProjections()
            .AddFiltering()
            .AddSorting()
            .AddDddTypes()
            .AddApplicationTypes();
```

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/Program.cs
> +            StoreAppsServiceDbProperties.ConnectionStringName);
Добавь elasticsearch, во все Program.cs, кроме aspire, после `builder.AddNpgsqlDbContext`

```
builder.AddElasticsearchClient("elasticsearch");
```

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/Properties/launchSettings.json
> +}
Удали файл, он не используется

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/StoreAppsServiceHttpApiHostModule.cs
> +    }
Поменяй последовательность методов, сначала OnPreApplicationInitializationAsync потом OnApplicationInitialization

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
Нет теста, если данный id не найден

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
Нет теста, если данное наименование уже существует

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
Нет теста, если данный id не найден

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
Нет теста, если данный id не найден

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
- Нет теста, если данный id не найден
- Нет теста, если данное наименование уже существует

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppQueriesTests.cs
> +    }
Нет теста, если данный id не найден

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppQueriesTests.cs
> +    }
Хотелось бы еще два-три тест с фильтрацией и что бы по версии тоже фильтровалось

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/Rubrum.Platform.StoreAppsService.Application.Tests.csproj
> +  </ItemGroup>
Убрать

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/AppMutationsTests.ActivateApp.snap
> +}
Побольше полей, кроме id

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/AppMutationsTests.ChangeNameApp.snap
> +}
Побольше полей, кроме id

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/AppMutationsTests.DeleteApp.snap
> +}
Побольше полей, кроме id

2024-10-13 16:26 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/Version.cs
> +public class Version : ValueObject
Не вижу тесты для версии на правильность ввода major, minor, patch

2024-10-13 17:32 UTC, vazgmik commented on services/blob-storage/test/Rubrum.Platform.BlobStorageService.Application.Tests/__snapshots__/SchemaTests.SchemaChangeTest.graphql
>    creationTime: DateTime
пока непонятно, возможно ребейз где-то что-то поменял, надо смотреть

2024-10-13 17:44 UTC, vazgmik commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Rubrum.Platform.StoreAppsService.Application.csproj
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
это убрать  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>?

2024-10-13 19:12 UTC, vazgmik commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/Properties/launchSettings.json
> +}
store-apps-service-dapr-cli без этого не стартует

2024-10-13 20:07 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Rubrum.Platform.StoreAppsService.Application.csproj
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
Да

2024-10-14 06:58 UTC, vazgmik commented on services/blob-storage/test/Rubrum.Platform.BlobStorageService.Application.Tests/__snapshots__/SchemaTests.SchemaChangeTest.graphql
>    creationTime: DateTime
кажется, изменения только в очередности полей, они у меня в другом порядке идут

2024-10-14 12:17 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.HttpApi.Host/Properties/launchSettings.json
> +}
Хммм, я думал в других сервисах его нет, буду разбираться

2024-10-14 16:52 UTC, vazgmik commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
+

2024-10-14 16:53 UTC, vazgmik commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
+

2024-10-14 16:53 UTC, vazgmik commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
+

2024-10-14 16:54 UTC, vazgmik commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
+

2024-10-14 16:55 UTC, vazgmik commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppMutationsTests.cs
> +    }
+

2024-10-14 16:55 UTC, vazgmik commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/AppQueriesTests.cs
> +    }
+

2024-10-14 17:47 UTC, Veribelll requested changes

2024-10-14 17:47 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/Commands/CreateAppCommand.cs
> +    public required AppVersion Version { get; init; }
Нет валидатора для AppVersion

2024-10-14 17:47 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.EntityFrameworkCore/StoreAppsServiceDbContextModelCreatingExtensions.cs
> +            b.ComplexProperty(x => x.Version, b1 =>
b1 на v поменяй, обычно тут принято использовать первую или две первых букв класса

2024-10-15 07:20 UTC, Veribelll approved these changes

2024-10-15 07:23 UTC, merged