Test winbox
rubrum-technologies/platform pull request #5
Opened 2024-09-09 21:13 UTC by vazgmik

2024-09-11 13:23 UTC, Veribelll requested changes

2024-09-11 13:23 UTC, Veribelll commented on app/package.json
> +    "@angular/cdk": "^18.2.3",
мы используем ~

Поставь версию 18.2.2 еще

2024-09-11 13:23 UTC, Veribelll commented on app/package.json
> +    "winbox": "0.2.82",
мы используем ~

2024-09-14 05:54 UTC, vazgmik commented on app/package.json
> +    "@angular/cdk": "^18.2.3",
поставил

2024-09-14 05:54 UTC, vazgmik commented on app/package.json
> +    "winbox": "0.2.82",
+

2024-09-15 15:49 UTC, merged