5 add store apps service
rubrum-technologies/platform pull request #6
Opened 2024-09-10 17:22 UTC by vazgmik

2024-09-17 05:49 UTC, Veribelll requested changes

2024-09-17 05:49 UTC, Veribelll commented on aspire/Rubrum.Platform.AppHost/Program.cs
> +    .WithYarpDaprRoute("/api/store-apps/{**everything}")
Лучше убери, тк у тебя там нет rest

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application.Contracts/AppExceptions.cs
> +public sealed class AppNotFoundException() : Exception("App not found.");
Это не нужно

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        var app = await appRepository.FindAsync(x => x.Id == appId, false, cancellationToken);
Просто GetAsync(id, true, ct)

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        CancellationToken cancellationToken = default)
cancellationToken => ct

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        CancellationToken cancellationToken = default)
cancellationToken => ct

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        CancellationToken cancellationToken = default)
cancellationToken => ct

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        CancellationToken cancellationToken = default)
cancellationToken => ct

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        CancellationToken cancellationToken = default)
cancellationToken => ct

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        var app = await appRepository.FindAsync(x => x.Id == appId, false, cancellationToken);
Просто GetAsync(id, true, ct)

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        var app = await appRepository.FindAsync(x => x.Id == appId, false, cancellationToken);
Просто GetAsync(id, true, ct)

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        var app = await appRepository.FindAsync(x => x.Id == input.AppId, false, cancellationToken);
Просто GetAsync(id, true, ct)

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +    public static async Task<App> CreateAppAsync(
[UseUnitOfWork]

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +    public static async Task<App> ChangeNameAsync(
[UseUnitOfWork]

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        [Service] AppManager appManager,
- просто repository
- просто manager

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +        UpdateAppInput input,
Расхождения Input и метода

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppApplicationService.cs
> +}
Удалить

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application.Contracts/UpdateAppInput.cs
> +    string Name);
В класс

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application.Contracts/CreateAppInput.cs
> +    bool Enabled);
В класс

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application.Contracts/CreateAppInput.cs
> +    [property: ID<App>] Guid? TenantId,
Удалить

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application.Contracts/CreateAppInput.cs
> +    [property: ID<App>] Guid? TenantId,
ID<App> на тенант не возможен

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +    public static async Task<App> DeleteAsync(
[UseUnitOfWork]

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +    public static async Task<App> ActivateAsync(
[UseUnitOfWork]

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +    public static async Task<App> DeactivateAsync(
[UseUnitOfWork]

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/VersionType.cs
> +}
Не имеет смысла в данном классе

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/App.cs
> +        Name = name;
Name должен всегда меняться через SetName

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/App.cs
> +    }
Разве тут нет сообщений про сортировку свойств и методов?

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/App.cs
> +    }
Тут точно должен быть warning

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/AppManager.cs
> +        Guid? tenantId,
Tenant задается через сервис CurrentTenant

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/Version.cs
> +        Check.Positive(major, "major must be greater than 0");
Если мне память не изменят, вторым аргументом должно быть название поля

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/Version.cs
> +    }
По любому тут warning

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/Version.cs
> +
Тут тоже warnings

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.EntityFrameworkCore/StoreAppsServiceDbContextModelCreatingExtensions.cs
> +            b.Property(x => x.Name).IsRequired();
Нет указания длины Name

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/SchemaTests.SchemaChangeTest.graphql
> +  changeName(input: ChangeNameInput!): ChangeNamePayload!
Изменения имени какой сущности?

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/SchemaTests.SchemaChangeTest.graphql
> +  delete(input: DeleteInput!): DeletePayload!
Удаление чего?

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/SchemaTests.SchemaChangeTest.graphql
> +  activate(input: ActivateInput!): ActivatePayload!
Активация чего?

2024-09-17 05:49 UTC, Veribelll commented on services/store-apps/test/Rubrum.Platform.StoreAppsService.Application.Tests/__snapshots__/SchemaTests.SchemaChangeTest.graphql
> +  deactivate(input: DeactivateInput!): DeactivatePayload!
Деактивация чего?

2024-09-17 20:55 UTC, vazgmik commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/App.cs
> +    }
выключен был монитор warnings)

2024-09-18 07:48 UTC, Veribelll requested changes

2024-09-18 07:48 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Domain/Apps/App.cs
> +    public Guid? TenantId { get; }
Сначала идут идентификаторы потом остальные поля

2024-09-18 07:48 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application.Contracts/CreateAppInput.cs
> +    public Guid? TenantId { get; init; }
Убрать, задается в manager через ICrurrentTenant

2024-09-19 05:29 UTC, Veribelll commented on services/store-apps/src/Rubrum.Platform.StoreAppsService.Application/Apps/AppMutations.cs
> +    public static async Task<App> DeactivateAppAsync(
Добавить под [UseUnitOfWork]

[UseAbpError]

2024-10-03 20:47 UTC, closed without merging